### ISSUE TITLE
Live demo code is on the way!

### ISSUE THREAD

**Issue by ZuoCX1996** [ZuoCX1996/Loose-Inertial-Poser#4]
In the past few days, I have received several questions about data formats and model invocation. So I will update **live demo code** in the coming days. I believe this is the best way to demonstrate the data processing and model calling workflow.

Thank you for your interest in Loose Inertial Poser!

**Comment by ZuoCX1996** [comment]
It's done!

**Comment by bryanbocao** [comment]
Awesome! Thanks for the demo code!
